# will never run on a git push or merge request event.
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always
    
variables:
  FULL_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  DH_IMAGE: cmptstks/wordpress
  DH_VERSION_TAG: php7.4-litespeed
    
default:
  tags:
    - shell
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    - echo "$DH_PW" | docker login -u $DH_USER --password-stdin
  after_script:
    - docker logout $CI_REGISTRY
    - docker logout
    
stages:
  - build
  - deploy
    
build:
  stage: build
  script:
    - "docker build -t $FULL_IMAGE php7.4-litespeed"
deploy:
  stage: deploy
  script:
    - "docker tag $FULL_IMAGE $CI_REGISTRY_IMAGE:$DH_VERSION_TAG"
    - "docker tag $FULL_IMAGE $CI_REGISTRY_IMAGE:latest"
    - "docker tag $FULL_IMAGE $DH_IMAGE:$DH_VERSION_TAG"
    - "docker tag $FULL_IMAGE $DH_IMAGE:latest"
    - "docker push $FULL_IMAGE"
    - "docker push $CI_REGISTRY_IMAGE:latest"
    - "docker push $CI_REGISTRY_IMAGE:$DH_VERSION_TAG"
    - "docker push $DH_IMAGE:php7.4-litespeed"
    - "docker push $DH_IMAGE:latest"
